### ISSUE TITLE
[HOST REQUEST]

### ISSUE THREAD

**Issue by TimboInSpace** [CarletonComputerScienceSociety/cloud-native#2]
**What is the project you want hosted? Describe it a bit**
NodeJS + Express + Pug webserver running my hobby project. The project is a single-page webapp running a game I wrote (working title: Word Torrent). It uses a mix of server-side and client-side rendering. Communication within the game is based on socket.io. There is no user-generated content and requires no account to play.

**What is the link to the repo?**
It's a private repo right now, but here it is:
[<link>](https://github.com/TimboInSpace/word-torrent)

**Any other info?**
Currently the game uses very little disk space and memory requirements are very low too. Later on, I will transition from in-memory storage to some kind of database or Redis. Feel free to dm me on Discord if you want to ask about it.

**Comment by AngelOnFira** [comment]
This sounds quite doable :)

The resource requirement sounds quite reasonable, as for a database down the line, Redis would be easy, other stateful databases would take a bit more work but wouldn't be too hard.

It doesn't look like a link to the repo worked. One of my requirements is that it needs to be open-source, will you be able to make it public?

As for hosting, do you have a domain name you'd like to use for it? Otherwise, I could get a subdomain for it on one of my domains :)

**Comment by AngelOnFira** [comment]
Closing this as it sounds like the project will remain closed source :+1:
